name: Build Flatpak

on:
  push:
    branches: [main]
    # only build when client/ edit
    paths:
      - "client/**"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder zip

      - name: Build Flatpak for aarch64
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          # Adjust the manifest file name if needed (e.g., flatpak-manifest.yaml)
          sudo flatpak-builder --force-clean --install-deps-from=flathub --arch=aarch64 --repo ./repo build-dir client/io.github.mentalbox.device.yaml
          # export to .flatpak bundle
          sudo flatpak build-bundle ./repo device.flatpak io.github.mentalbox.device

      # - name: make tar Repository
      #   run: sudo tar -czvf  repo.tar.gz ./repo

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: device.flatpak
          path: device.flatpak 
        